#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:nil todo:t |:t
#+title: A Christmas Tautology
#+date: <2020-12-12 Sat>
#+author: Nick Drozd
#+email: nicholasdrozd@gmail.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.0.50 (Org mode 9.3)
#+jekyll_layout: post
#+jekyll_categories:
#+jekyll_tags:

There is a well-known *Christmas carol* that starts out like this:

#+begin_src
God rest you merry gentlemen
Let nothing you dismay
Remember Christ our saviour
Was born on Christmas Day
#+end_src

Another carol has this verse:

#+begin_src
The holly bears a prickle
As sharp as any thorn
And Mary bore sweet Jesus Christ
On Christmas Day in the morn
#+end_src

These lyrics always bothered me for their apparent *vacuousness*. /Christ was born on Christmas Day/ -- well, yeah. Christmas /just is/ the day that Christ was born, right? /Mary bore Jesus Christ on Christmas day/ -- *no shit*! She couldn't have born him on any other day even if she wanted to! If she had born Christ on any other day, that day would /thereby just have been/ Christmas Day.

That Christ was born on Christmas Day is an example of what philosophers call an */analytic proposition/*, a proposition that is true by virtue of its meaning. Analytic propositions are contrasted with */synthetic propositions/*, which are true according as whether or not they accurately describe the state of things. Here's a synthetic proposition: /"Dwight Eisenhower was born on Christmas Day."/ Is that true? I just made it up, so probably not, but it could be. Determining the truth of that claim would require looking up Eisenhower's date of birth and checking if it was Christmas or not. But nothing needs to be looked up to verify that Christ was born on Christmas Day -- that's just what it /means/ to /be/ Christmas Day.

That's what I thought, anyway, but it turns out that *none of that is true*. The word /Christmas/ is a shortening of /Christ's mass/ (as in, "church mass"). There are [[https://en.wiktionary.org/wiki/Category:English_words_suffixed_with_-mas][other names of the form ____-/mas/]], like: /[[https://en.wikipedia.org/wiki/Martinmas][Martinmas]]/, /[[https://en.wikipedia.org/wiki/Michaelmas][Michaelmas]]/, /[[https://en.wikipedia.org/wiki/Childermas][Childermas]]/, and /[[https://en.wikipedia.org/wiki/Candlemas][Candlemas]]/. None of these events pertain to births. Martinmas is on the day of Martin's funeral; Michaelmas has to do with the angel Michael, and I don't know that the particular day has any significance; Childermas commemorates the [[https://en.wikipedia.org/wiki/Massacre_of_the_Innocents]["Massacre of the Innocents"]]; and Candlemas doesn't have anything to do with any specific people at all, just candles.

*It isn't the case that Christmas "just is" the day that Christ was born.* It's the festival that commemorates Christ, and it happens to fall on the birth of Christ, but it could have been set on some other day instead. So when these carols say that Christ was born on Christmas Day, they are not saying something trivially, analytically true.

Okay, but isn't it still *obvious* that Christ was born on Christmas Day? Doesn't everyone already know that? Why bother mentioning it? According to my [[https://en.wikipedia.org/wiki/Christmas#Modern_history][cursory Wikipedia research]], this was not always the case:

#+begin_quote
Associating it with *drunkenness and other misbehaviour*, the Puritans *banned Christmas* in England in the 17th century. It was restored as a legal holiday in 1660, but remained *disreputable*... *Charles Dickens* and other writers helped in this revival of the holiday by "changing consciousness of Christmas and the way in which it was celebrated" as they emphasized family, religion, gift-giving, and social reconciliation as opposed to the historic revelry common in some places.
#+end_quote

The modern *rehabilitation of Christmas* as a time for thanks and family and blah blah blah didn't take hold until the 19th century. But the carols quoted above were written before then. Maybe when they were first developed, the knowledge that Christ was born on Christmas Day was not widespread, and would have been considered non-obvious. Maybe it even took a tone of *admonishment*: uptight carolers come upon some drunken Christmas revelers, and say "Hey now, take this seriously! Remember, Christ was /born/ on Christmas Day!"

A critical point to keep in mind when engaging in *textual interpretion* is that /the reader(s) and writer(s) of a text might have dramatically different knowledge, background assumptions, and purposes/. Those carols were not developed with a "modern" understanding of Christmas; if they had been, they probably would not have included lyrics that seem stupid to modern ears.

A more superficial example of the same point is the /*rotted rhymes*/ of *"The Holly and the Ivy"*. I don't know if there is an established term for this, but what I mean is words that used to rhyme, but now don't, and therefore sound bad. Consider:

#+begin_src
The holly and the ivy
When they are both full GROWN
Of all the trees that are in the wood
The holly bears the CROWN

The rising of the sun
And the running of the DEER
The playing of the merry organ
Sweet singing in the CHOIR

The holly bears a berry
As red as any BLOOD
And Mary bore sweet Jesus Christ
For to do us sinners GOOD
#+end_src

Words in all-caps *do not rhyme anymore*, at least not in modern American English, but apparently [[https://english.stackexchange.com/questions/477873/have-choir-and-deer-ever-rhymed][they used to]]. Even if there were no other corroborating evidence that these words used to rhyme, the *[[https://en.wikipedia.org/wiki/Principle_of_charity][principle of charity]]* would lead to the hypothesis that they did. After all, there are basically only two possibilities: 1) the words used to rhyme, or 2) these lyrics are dumb. The second possibility is not a charitable interpretation, so the first should be assumed, at least as a working hypothesis.

* Discussion Questions

1. What is the correct punctuation the line "God rest you merry genlemen"?
2. How sharp is the distinction between "analytic" and "synthetic" propositions?
3. How is it possible to misidentify a synthetic proposition as an analytic one?
4. When was Dwight Eisenhower born?
5. Is there an exhaustive list of ____-/mas/ words?
6. Is the confusion exhibited in this post just an artifact of English, or does it occur in other languages?
7. Do the lyrics of "The Holly and the Ivy" still rhyme anywhere?
8. Was Christ really born on Christmas Day?
9. Was "Christ" really born at all?
