#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:nil todo:t |:t
#+title: Derek Chauvin Did This
#+date: <2020-05-30 Sat>
#+author: Nick Drozd
#+email: nicholasdrozd@gmail.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.0.50 (Org mode 9.3)
#+jekyll_layout: post
#+jekyll_categories:
#+jekyll_tags:

On the evening of May 25, 2020, *Derek Chauvin murdered George Floyd in Minneapolis*. Chauvin was a White cop, and Floyd was an unarmed Black man. People got angry and they started protesting in Minneapolis and St Paul. *Peaceful protests* turned into *destructive riots*, and buildings have been burned. *I personally witnessed a gas station get looted and then burned.*

A common response to this kind of thing from the *moderate left* is:

#+begin_quote
I am in favor of peaceful protest, but I don't support looting and the destruction of property. That just hurts small business owners, many of whom were already in bad shape from the coronavirus shutdown.
#+end_quote

*It's true that looting hurts small business owners.* People living in nearby neighborhoods are affected as well. Hell, if the Twin Cities turn out like Detroit, ill consequences will be felt for generations to come, and *things might never recover*.

And you know what? *It's all Derek Chauvin's fault.*

Chauvin held his knee to Floyd's neck for *eight minutes*, and Floyd was unconscious for the last four of those. That is a *really long time* to hold someone down. His adrenaline wasn't pumping, and he didn't have to make any snap decisions. *Chauvin had plenty of time to consider the consequnces of his actions, and he chose to murder Floyd anyway.*

At any point in those eight minutes, he might have stopped and thought *"Is what I'm doing conducive to order and public safety?"* He might have considered that there were protests in the Twin Cities just three years ago, when *Jeronimo Yanez* was found not guilty in the killing of *Philando Castille*. He might also have considered that we are in the midst of the *coronavirus lockdown* and its associated *economic crisis*, and that consequently everyone is already on edge. He might even have just looked around and realized that he was choking the life out of a handcuffed prisoner *in broad daylight, in full view of witnesses with cameras*.

*Any of those considerations might have caused Chauvin to relent.* If he had, Floyd would have lived, and protestors would not have taken to the streets, and businesses would not have been destroyed. The underlying problems would still persist, of course, but there wouldn't have been a spark to set off riots.

Instead, *Derek Chauvin chose in cold blood to murder George Floyd*. He alone made that choice, but we all have to live with the consequences. *He is responsible for all of it.* If he hadn't chosen to do what he did, there wouldn't have been any looting or any burning, because nothing would have happened.

And what good did his choice do? He was a cop (since fired), so his job was to maintain public order. *Was murdering a handcuffed prisoner in the best interest of public order? Did it make the city more safe, or less safe?* *Did the people of Minneapolis benefit?* He had eight minutes to think about those questions, and in the end, he decided to go ahead with the murder.

If you're upset about looting and property damage and businesses burning down, don't blame the protesters. *Blame Derek Chauvin. He did this.*
