#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: The Pronunciation of 'Kernighan', according to Foreign-Language Wikipedia
#+date: <2020-05-28 Thu>
#+author: Nick Drozd
#+email: nicholasdrozd@gmail.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.0.50 (Org mode 9.3)
#+jekyll_layout: post
#+jekyll_categories:
#+jekyll_tags:

* Intro

*"Kernighan"*. It's the "k" in *=awk=*. *But how is it pronounced?* In particular, how should the *"gh" digraph* be handled? This is something of a shibboleth in programmer circles. The obvious way is to say the "gh" as a *"g"*, so that "Kernighan" rhymes with *"turn again"*. But Brian Kernighan himself, followed by those "in the know", pronounces the "gh" as an *"h"*, as in *"turn a hand"*. He says so in [[https://www.cs.cmu.edu/~mihaib/kernighan-interview/][this interview]]:

#+begin_quote
M: What is the correct way to pronounce your name? I heard that it is not the obvious way?

K: It's pronounced Kernihan, *the g is silent*.
#+end_quote

Now, imagine that you are writing a *Wikipedia article about Brian Kernighan* in a language other than [[https://en.wikipedia.org/wiki/Brian_Kernighan][English]]. What do you do about the pronunciation of that name? If you are writing in a lanugage that uses the *Roman alphabet*, then you can *punt* on the issue by using the English spelling and leaving the pronunciation unclear. This is done in the Brian Kernighan Wikipedia articles in [[https://id.wikipedia.org/wiki/Brian_Kernighan][Indonesian]], [[https://ku.wikipedia.org/wiki/Brian_Kernighan][Kurdish]], [[https://hu.wikipedia.org/wiki/Brian_Kernighan][Hungarian]], and all other Roman-alphabet languages. A few of them specify the actual pronunciation, but most of them don't.

However, if you are writing in a script other than the Roman alphabet, you will be forced to *disambiguate* the "gh" digraph and *commit* to some pronunciation or other. What follows is a survey of these *transliterations* (as of May 2020). My knowledge of these languages and their writing systems is somewhat patchy, and more knowledgeable readers will surely be able to correct me in places. On the other hand, relatively few people take a bird's-eye view to orthography across languages, so hopefully every reader will find something interesting.

Languages will be grouped as *West Asian*, *East Asian*, and *South Asian*.

* *West Asian*
** Arabic Script
*** [[https://ar.wikipedia.org/wiki/%D8%A8%D8%B1%D8%A7%D9%8A%D9%86_%D9%83%D9%8A%D8%B1%D9%86%D9%8A%D8%BA%D8%A7%D9%86][Standard Arabic]] : براين كيرنيغان
    The "gh" is represented by *[[https://en.wikipedia.org/wiki/%D8%BA][غ]]*. Normally this letter represents a throaty sound somelike like the French "r", but in foreign words it is sometimes used for "g". Going from Arabic to English, it is often represented as "gh", as in /Baghdad/ بغداد.

*** [[https://arz.wikipedia.org/wiki/%D8%A8%D8%B1%D8%A7%D9%8A%D9%86_%D9%83%D9%8A%D8%B1%D9%86%D9%8A%D8%AC%D8%A7%D9%86][Egyptian Arabic]] : براين كيرنيجان
    The "gh" is represented by *[[https://en.wikipedia.org/wiki/%D8%AC][ج]]*. Normally this letter makes a "j" sound, as in /James/, but in Egypt it is pronounced as a "g". The Arabic name for Egypt is /Misir/. Misir loves company.

*** [[https://fa.wikipedia.org/wiki/%D8%A8%D8%B1%D8%A7%DB%8C%D8%A7%D9%86_%DA%A9%D8%B1%D9%86%DB%8C%DA%AF%D8%A7%D9%86][Persian]] : برایان کرنیگان
    The "gh" is represented by *[[https://en.wikipedia.org/wiki/%DA%AF][گ]]*, which is just "g". It's one of a handful of letters used in Persian (and languages like Urdu) that is not used in Arabic, though it is a variation of *[[https://en.wikipedia.org/wiki/%DA%A9][ک]]*, "k", which is used as the "K" in "Kernighan".

*** [[https://azb.wikipedia.org/wiki/%D8%A8%D8%B1%D8%A7%DB%8C%D8%A7%D9%86_%DA%A9%D8%B1%D9%86%DB%8C%D9%82%D8%A7%D9%86][Azeri Turkish (Iranian)]] : برایان کرنیقان
    The "gh" is represented by *[[https://en.wikipedia.org/wiki/%D9%82][ق]]*. In Arabic, this letter represents a throaty sound that is distinct from ﻍ, but in Persian the two letters are pronounced the same. I don't know for sure, but I assume the same is true in Azeri Turkish (as spoken in northern Iran). In any case, this is a "g"-like sound.

** Armenian : Բրայան Կերնիգան
   No entry for Brian Kernighan, but there is an article on *[[https://hy.wikipedia.org/wiki/AWK][AWK]]*, and it refers to Բրայան Կերնիգան. The "gh" is represented by *գ*. Different dialects of Armenian *swap voicings* for certain consonants, and գ is sometimes pronounced as "g" and sometimes as "k". For that matter, *Կ* is sometimes pronounced as "k" and sometimes as "g", so Կերնիգան could be pronounced as "Kernigan" or "Gernikan".

** Cyrillic
*** [[https://mk.wikipedia.org/wiki/%D0%91%D1%80%D0%B0%D1%98%D0%B0%D0%BD_%D0%9A%D0%B5%D1%80%D0%BD%D0%B8%D1%85%D0%B0%D0%BD][Macedonian]] : Брајан Кернихан
    The "gh" is represented by *[[https://en.wikipedia.org/wiki/Kha_(Cyrillic)][х]]*, which is used for an unvoiced throat sound. Slavic languages mostly lack a pure "h" sound, so I am inclined to call this "h"-like.

*** [[https://ru.wikipedia.org/wiki/%D0%9A%D0%B5%D1%80%D0%BD%D0%B8%D0%B3%D0%B0%D0%BD,_%D0%91%D1%80%D0%B0%D0%B9%D0%B0%D0%BD][Russian]] : Брайан Керниган
    The "gh" is represented by *[[https://en.wikipedia.org/wiki/Ge_(Cyrillic)][г]]*, which is usually pronounced as "g", though some dialects pronounce it more like "h". According to Wikipedia, it often used to represent "h" in foreign words, as in Гарри Поттер for "Harry Potter".

*** [[https://sr.wikipedia.org/wiki/%D0%91%D1%80%D0%B0%D1%98%D0%B0%D0%BD_%D0%9A%D0%B5%D1%80%D0%BD%D0%B8%D0%B3%D0%B5%D0%BD][Serbian]] : Брајан Керниген
    Same as entry for Russian.

*** [[https://uk.wikipedia.org/wiki/%D0%91%D1%80%D0%B0%D1%8F%D0%BD_%D0%9A%D0%B5%D1%80%D0%BD%D1%96%D0%B3%D0%B0%D0%BD][Ukranian]] : Браян Керніган
    The "gh" is represented by *[[https://en.wikipedia.org/wiki/Ge_(Cyrillic)][г]]*, which in Ukranian is pronounced as "h".

** Georgian : ბრაიან კერნიგენი
   No entry for Brian Kernighan, but there is an article on *[[https://ka.wikipedia.org/wiki/Hello_world]["Hello world"]]* (გამარჯობა სამყარო), and it refers to ბრაიან კერნიგენი. The important letter there is *[[https://en.wikipedia.org/wiki/Gani_(letter)][გ]]*, which is a "g".

** Greek : Μπράιαν Κέρνιχαν
   Greek Wikipedia doesn't have an entry for Brian Kernighan, but there is one for */[[https://el.wikipedia.org/wiki/The_C_Programming_Language][The C Programming Language]]/*. It mentions *Μπράιαν Κέρνιχαν*, using the "h"-like *χ* for "gh". There is also an article on *[[https://el.wikipedia.org/wiki/AWK][AWK]]*, and it mentions "Brian Kernighan". *Untransliterated Roman-alphabet text is mixed freely into the surrounding Greek:*
   #+begin_quote
   Η AWK δημιουργήθηκε στα Bell Labs στα τέλη της δεκαετίας του 1970, και το όνομά της προέρχεται από τα επίθετα των δημιουργών της — Alfred Aho, Peter Weinberger και Brian Kernighan.
   #+end_quote
   *Is this a common practice in Greek?*

** [[https://he.wikipedia.org/wiki/%D7%91%D7%A8%D7%99%D7%90%D7%9F_%D7%A7%D7%A8%D7%A0%D7%99%D7%92%D7%94%D7%90%D7%9F][Hebrew]] : בריאן קרניגהאן
   This is a curious choice, as the "gh" is represented letter-for-letter as *[[https://en.wikipedia.org/wiki/%D7%92][ג]]* and then *[[https://en.wikipedia.org/wiki/%D7%94][ה]]*. I don't know how this combination is pronounced, or if it is standard in Hebrew. There don'e seem to be any mentions of Brian Kernighan on *Yiddish* Wikipedia, although the entry on *[[https://yi.wikipedia.org/wiki/%2B%2BC][C++]]* does mention *Bjarne Stroustrup*, *ביארנע סטרויסטרופ*. The [[https://he.wikipedia.org/wiki/%D7%91%D7%99%D7%90%D7%A8%D7%9F_%D7%A1%D7%98%D7%A8%D7%95%D7%A1%D7%98%D7%A8%D7%95%D7%A4][Hebrew article]] spells his name *ביארן סטרוסטרופ*

* *East Asian*
** [[https://zh.wikipedia.org/wiki/%E5%B8%83%E8%90%8A%E6%81%A9%C2%B7%E6%9F%AF%E6%9E%97%E6%BC%A2][Chinese]] : 布萊恩·柯林漢
   The "ghan" is represented by *漢*, /han/. Chinese is not written using *letters*, but rather with a dizzying array of *[[https://nickdrozd.github.io/2020/03/09/chinese.html][characters]]*. The characters are associated with both sounds and meanings. There is apparently a somewhat standard method for [[https://en.wikipedia.org/wiki/Transcription_into_Chinese_characters][transcribing foreign words into Chinese]].
   - Brian
     - [[https://en.wiktionary.org/wiki/%E5%B8%83][布]] /bu/
     - [[https://en.wiktionary.org/wiki/%E8%90%8A][萊]] /lai/
     - [[https://en.wiktionary.org/wiki/%E6%81%A9][恩]] /en/
   - Kernighan
     - [[https://en.wiktionary.org/wiki/%E6%9F%AF][柯]] /ke/
     - [[https://en.wiktionary.org/wiki/%E6%9E%97][林]] /lin/
       - This seems to be *phonetically wrong*. Accepting "l" in place of "r", shouldn't this sound like "lni", as in "kelnihan"?
       - Perhaps 林 was chosen because it's a common Chinese surname, and Kernighan is a surname. Is *thematic accuracy* an important consideration?
       - In *Cantonese*, 林 is pronounced "lam", as in [[https://en.wikipedia.org/wiki/Carrie_Lam][Carrie Lam]] 林鄭月娥.
     - [[https://en.wiktionary.org/wiki/%E6%BC%A2][漢]] /han/
       - This is the name of the Han Chinese people.
       - The "simplified" form of this character is [[https://en.wiktionary.org/wiki/%E6%B1%89][汉]].

** [[https://ja.wikipedia.org/wiki/%E3%83%96%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%BB%E3%82%AB%E3%83%BC%E3%83%8B%E3%83%8F%E3%83%B3][Japanese]] : ブライアン・カーニハン
   As is typical for foreign words, this name is written using *[[https://en.wikipedia.org/wiki/Katakana][katakana]]* letters. The "gh" is represented with *ハ*, /ha/. In *[[https://en.wikipedia.org/wiki/Hiragana][hiragana]]* letters, this name would be written as *ぶらいあん・かにはん*.
   - Brian
     - [[https://en.wikipedia.org/wiki/Fu_(kana)][ブ]] /bu/
     - [[https://en.wikipedia.org/wiki/Ra_(kana)][ラ]] /ra/
     - [[https://en.wikipedia.org/wiki/I_(kana)][イ]] /i/
     - [[https://en.wikipedia.org/wiki/A_(kana)][ア]] /a/
     - [[https://en.wikipedia.org/wiki/N_(kana)][ン]] /n/
   - Kernighan
     - [[https://en.wikipedia.org/wiki/Ka_(kana)][カ]] /ka/
     - [[https://en.wikipedia.org/wiki/Ch%C5%8Donpu][ー]] (long sound marker)
     - [[https://en.wikipedia.org/wiki/Ni_(kana)][ニ]] /ni/
     - [[https://en.wikipedia.org/wiki/Ha_(kana)][ハ]] /ha/
     - [[https://en.wikipedia.org/wiki/N_(kana)][ン]] /n/

** [[https://ko.wikipedia.org/wiki/%EB%B8%8C%EB%9D%BC%EC%9D%B4%EC%96%B8_%EC%BB%A4%EB%8B%88%ED%95%B8][Korean]] : 브라이언 커니핸
   The [[https://en.wikipedia.org/wiki/Hangul][Korean alphabet]] is written as individual letters composed into syllable blocks. The "ghan" is represented as *핸*, /hen/. This is similar to *한*, /han/, which is the first syllable in the Korean name of the alphabet, /*hangul*/.
   - Brian
     - 브 /bu/
     - 라 /rah/
     - 이 /i/
     - 언 /un/
   - Kernighan
     - 커 /kuh/
     - 니 /ni/
     - 핸 /hen/
       - [[https://en.wikipedia.org/wiki/%E3%85%8E][ㅎ]]

* *South Asian*
  There are three South Asian language articles about Brian Kernighan: *Bengali*, *Malayalam*, and *Marathi*. I don't know much about South Asian languages or their alphabets. I don't even know enough to get started on researching it, so I won't try. My question is: *Why are there Brian Kernighan articles in these languages, but not in Hindi or Urdu?*
** [[https://bn.wikipedia.org/wiki/%E0%A6%AC%E0%A7%8D%E0%A6%B0%E0%A6%BE%E0%A6%AF%E0%A6%BC%E0%A6%BE%E0%A6%A8_%E0%A6%89%E0%A6%87%E0%A6%B2%E0%A6%B8%E0%A6%A8_%E0%A6%95%E0%A6%BE%E0%A6%B0%E0%A7%8D%E0%A6%A8%E0%A6%BF%E0%A6%82%E0%A6%B9%E0%A6%BE%E0%A6%A8][Bengali]] : ব্রায়ান উইলসন কার্নিংহান
** [[https://ml.wikipedia.org/wiki/%E0%B4%AC%E0%B5%8D%E0%B4%B0%E0%B4%AF%E0%B4%BE%E0%B5%BB_%E0%B4%95%E0%B5%86%E0%B5%BC%E0%B4%A3%E0%B4%BF%E0%B4%B9%E0%B4%BE%E0%B5%BB][Malayalam]] : ബ്രയാൻ കെർണിഹാൻ
** [[https://mr.wikipedia.org/wiki/%E0%A4%AC%E0%A5%8D%E0%A4%B0%E0%A4%BE%E0%A4%AF%E0%A4%A8_%E0%A4%95%E0%A5%87%E0%A4%B0%E0%A5%8D%E0%A4%A8%E0%A4%BF%E0%A4%98%E0%A4%A8][Marathi]] : ब्रायन केर्निघन
